name: End to end tests

on:
  push:
  schedule:
    - cron: '0 18 * * 0' # Runs every Sunday at 6:00 PM UTC
  workflow_dispatch:
permissions: write-all
env:
  CYPRESS_SUBMIT_USER_EMAIL: "${{ secrets.SUBMIT_USER_EMAIL }}"
  CYPRESS_SUBMIT_USER_PASSWORD: "${{ secrets.SUBMIT_USER_PASSWORD }}"
  CYPRESS_SEARCH_USER_EMAIL: "${{ secrets.SEARCH_USER_EMAIL }}"
  CYPRESS_SEARCH_USER_PASSWORD: "${{ secrets.SEARCH_USER_PASSWORD }}"
  CYPRESS_SUPPORT_USER_EMAIL: "${{ secrets.SUPPORT_USER_EMAIL }}"
  CYPRESS_SUPPORT_USER_PASSWORD: "${{ secrets.SUPPORT_USER_PASSWORD }}"
  CYPRESS_TWO_FACTOR_AUTH_KEY: "${{ secrets.TWO_FACTOR_AUTH_KEY }}"
  CYPRESS_RP: "${{ secrets.RP }}"
  CYPRESS_BASIC_AUTH_USERNAME: "${{ secrets.BASIC_AUTH_USERNAME }}"
  CYPRESS_BASIC_AUTH_PASSWORD: "${{ secrets.BASIC_AUTH_PASSWORD }}"
  CYPRESS_RECORD_KEY: "${{ secrets.CYPRESS_RECORD_KEY }}"
jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
