'on': push
workflow_dispatch:
  inputs:
    trigger_uuid:
      description: the trigger UUIID for which we will create an artifact
      required: false
name: End-to-end tests

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
      - name: Create Run UUID Artifact
        if: github.event.inputs.trigger_uuid != ''
        run: >
          echo
          $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID |
          \
              tee /tmp/${{ github.event.inputs.trigger_uuid }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Upload UUID As An Artifact
        uses: actions/upload-artifact@v2
        if: '${{ always() && github.event.inputs.trigger_uuid != '''' }}'
        with:
          name: '${{ github.event.inputs.trigger_uuid }}'
          path: '/tmp/${{ github.event.inputs.trigger_uuid }}'